version: '3'
services:
  chat2db:
    image: chat2db/chat2db:latest
    container_name: chat2db-dev
    volumes:
      - ~/.chat2db-docker:/root/.chat2db
    ports:
      - "10824:10824"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
